imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      ~ #{ fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# ------------------------------------------------- #
# ---------------- TWIG CONFIGURATION ------------- #
# ------------------------------------------------- #

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


# ------------------------------------------------- #
# ------------- ASSETIC CONFIGURATION ------------- #
# ------------------------------------------------- #

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# ------------------------------------------------- #
# ------------ DOCTRINE CONFIGURATION ------------- #
# ------------------------------------------------- #

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# ------------------------------------------------- #
# --------- SWIFTMAILER CONFIGURATION ------------- #
# ------------------------------------------------- #

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# ------------------------------------------------- #
# --------------- FOS User Manager ---------------- #
# ------------------------------------------------- #
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\Usuario


# ------------------------------------------------- #
# ----------- DOCUMENTACIÓN API REST -------------- #
# ------------------------------------------------- #

nelmio_api_doc:
    name: 'Documentación APIREST Reserving'

jms_serializer:
    visitors:
        json:
            options: [JSON_UNESCAPED_SLASHES, JSON_UNESCAPED_UNICODE]

# ------------------------------------------------- #
# -------------- NELMIO CROS BUNDLE --------------- #
# ------------------------------------------------- #
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            expose_headers: ['*']
            max_age: 0


# ------------------------------------------------- #
# ----------- SENSIO_FRAMEWORK_EXTRA -------------- #
# ------------------------------------------------- #

sensio_framework_extra:
    # desactiva la anotación View para este bundle, así no colisiona con FOSRestBundle
    view:    { annotations: false }

    # activa los conversores para poder utilizar ParamConverters con los datos que llegan en el request
    request: { converters: true }

# ------------------------------------------------- #
# ------------------ FOSRESTBUNDLE ---------------- #
# ------------------------------------------------- #

fos_rest:
    view: #activa las vistas para el bundle
        view_response_listener: force

    body_converter:
        enabled: true

    format_listener:
        rules:
            - { path: '/', host: '%api_domain%', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: ^/, host: '%domain%', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: false }
            - { path: ^/, host: '%app_domain%', priorities: ['html', '*/*'], fallback_format: html, prefer_extension: false }

    routing_loader:
        default_format: json
        include_format: false

    body_listener: #el decoder es el de JSON
        decoders:
            json: fos_rest.decoder.json
