reserving_api_routing:
    resource: "@AppBundle/Resources/config/api_routing.yml"
    type: rest
    prefix:   /
    host: %api_domain%


reserving_admin_routing:
    resource: "@AppBundle/Resources/config/admin_routing.yml"
    prefix:   /app
    host: %domain%

reserving_web_routing:
    resource: "@AppBundle/Resources/config/web_routing.yml"
    prefix:   /
    host: %domain%

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc/
    host: %api_domain%
