reserving_api_routing:
    resource: "@AppBundle/Resources/config/api_routing.yml"
    type: rest
    prefix:   /
    host: %api_domain%

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /
    host: %api_domain%

reserving_admin_routing:
    resource: "@AppBundle/Resources/config/admin_routing.yml"
    prefix:   /
    host: %app_domain%

reserving_web_routing:
    resource: "@AppBundle/Resources/config/web_routing.yml"
    prefix:   /
    host: %domain%


# ------------------------------------------------- #
# ----------- RUTAS DE FOSUserBundle -------------- #
# ------------------------------------------------- #

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    host: %domain%

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    host: %domain%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    host: %domain%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    host: %domain%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    host: %domain%
