# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:

    #-----------------------------------------------------------#
    #------- CONFIGURACIÓN CODIFICADOR DE CONTRASEÑAS ----------#
    #-----------------------------------------------------------#
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512


    #-----------------------------------------------------------#
    #-------------- CONFIGURACIÓN ROLES DE USUARIOS ------------#
    #-----------------------------------------------------------#
    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]



    #-----------------------------------------------------------#
    #---------- CONFIGURACIÓN PROVEEDOR DE USUARIOS ------------#
    #-----------------------------------------------------------#
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email


    #-----------------------------------------------------------#
    #---------- CONFIGURACIÓN DE SEGURADA - FIREWALL -----------#
    #-----------------------------------------------------------#
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            pattern: ^/
            host: "%domain%"
            form_login:
                provider: fos_userbundle
                login_path: /login
                always_use_default_target_path: false
                default_target_path: /app
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:
                path:   /logout
                target: /
            anonymous:    true



    #--------------------------------------------------------------#
    #---------- CONFIGURACIÓN DE ACCESO A LA APLICACIÓN -----------#
    #--------------------------------------------------------------#
    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY} #, requires_channel: https }
        - { host: %domain%, path: ^/app, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER, host: "app.%domain%" }
        #- { path: ^/, roles: ROLE_ADMIN, host: "api.%domain%" }