api_empleado:
    type: rest
    resource: AppBundle\Controller\UsuarioController

api_cliente:
    type: rest
    resource: AppBundle\Controller\ClienteController


api_servicio:
    type: rest
    resource: AppBundle\Controller\ServicioController

api_empleado:
    type: rest
    resource: AppBundle\Controller\EmpleadoController