api_usuario:
    type: rest
    resource: AppBundle\Controller\UsuarioController

api_cliente:
    type: rest
    resource: AppBundle\Controller\ClienteController


api_servicio:
    type: rest
    resource: AppBundle\Controller\ServicioController

api_empleado:
    type: rest
    resource: AppBundle\Controller\EmpleadoController

api_cita:
    type: rest
    resource: AppBundle\Controller\CitaController


# Rutas combinadas #

api_usuario_cliente:
    type:     rest
    parent:   api_usuario
    resource: AppBundle\Controller\UsuarioClienteController