services:
#    app.example:
#        class: AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


    # ----------------------------------------------------- #
    # --------------- REGISTRATION SERVICE ---------------- #
    # ----------------------------------------------------- #
    app_user.registration.form.type:
        class: AppBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }