web_homepage:
    path:     /
    defaults: { _controller: AppBundle:Web:index }

web_servicios:
    path:     /servicios/
    defaults: { _controller: AppBundle:Web:servicios }

web_preguntas_frecuentes:
    path:     /preguntas-frecuentes/
    defaults: { _controller: AppBundle:Web:faq }
